package za.co.wethinkcode.ServerClient.database.dao;

import net.lemnik.eodsql.AutoGeneratedKeys;
import net.lemnik.eodsql.ResultColumn;
import org.json.JSONObject;

public class ObstacleDAO {

    @AutoGeneratedKeys
    @ResultColumn(value = "id")
    private int id;

    @ResultColumn(value = "size")
    private int size;

    @ResultColumn(value = "world_id")
    private int worldId;

    @ResultColumn(value = "position")
    private String position;

    public int getId() {
        return id;
    }

    public int getSize() {
        return size;
    }

    public void setSize ( int size ) {
        this.size = size;
    }

    public int getWorldId() {
        return worldId;
    }

    public void setWorldId ( int worldId ) {
        this.worldId = worldId;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition( String position) {
        this.position = position;
    }

    public static ObstacleDAO create(int size, int worldId, String position) {
        ObstacleDAO obstacle = new ObstacleDAO();
        obstacle.setSize(size);
        obstacle.setPosition(position);
        obstacle.setWorldId(worldId);
        return obstacle;
    }

    public static ObstacleDAO createFromJsonObject(JSONObject jsonObject) {
        ObstacleDAO obstacle = new ObstacleDAO();
        obstacle.setPosition(jsonObject.getString("position"));
        obstacle.setSize(jsonObject.getInt("size"));
        obstacle.setWorldId(jsonObject.getInt("worldId"));
        return obstacle;
    }
}