package za.co.wethinkcode.ServerClient.database.dao;

import net.lemnik.eodsql.AutoGeneratedKeys;
import net.lemnik.eodsql.ResultColumn;

public class RobotDAO {

    @AutoGeneratedKeys
    @ResultColumn(value = "id")
    private int id;

    @ResultColumn(value = "world_id")
    private int worldId;

    @ResultColumn(value = "position")
    private String position;

    @ResultColumn(value = "name")
    private String name;

    @ResultColumn(value = "direction")
    private String direction;

    public int getId() {
        return id;
    }

    public int getWorldId() {
        return worldId;
    }

    public void setWorldId ( int worldId ) {
        this.worldId = worldId;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDirection() {
        return direction;
    }

    public void setDirection(String direction) {
        this.direction = direction;
    }

    public static RobotDAO create(String name, int worldId, String position, String direction) {
        RobotDAO robot = new RobotDAO();
        robot.setName(name);
        robot.setWorldId(worldId);
        robot.setPosition(position);
        robot.setDirection(direction);
        return robot;
    }
}
