package za.co.wethinkcode.ServerClient.database.dao;

import net.lemnik.eodsql.AutoGeneratedKeys;
import net.lemnik.eodsql.ResultColumn;

public class ServerDAO {

    @AutoGeneratedKeys
    @ResultColumn(value = "id")
    private int id;

    @ResultColumn(value = "port")
    private int port;

    @ResultColumn(value = "ip")
    private String ip;

    @ResultColumn(value = "name")
    private String name;

    public int getId() {
        return id;
    }

    public int getPort() {
        return port;
    }

    public void setPort ( int port ) {
        this.port = port;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public static ServerDAO create (String name, int port, String ip) {
        ServerDAO server = new ServerDAO();
        server.setName(name);
        server.setPort(port);
        server.setIp(ip);
        return server;
    }
}
